locals {
  worker_node_group_key = "default"

  worker_iam_role_arn = try(
    module.eks.self_managed_node_groups[local.worker_node_group_key].iam_role_arn,
    null,
  )

  aws_auth_roles = [
    {
      rolearn  = local.worker_iam_role_arn
      username = "system:node:{{EC2PrivateDNSName}}"
      groups = [
        "system:bootstrappers",
        "system:nodes",
      ]
    }
  ]

  aws_auth_users = [
    for u in var.map_users : {
      userarn  = u.userarn
      username = u.username
      groups   = u.groups
    }
  ]

  aws_auth_data = merge(
    {
      mapRoles = yamlencode(local.aws_auth_roles)
    },
    length(local.aws_auth_users) > 0 ? {
      mapUsers = yamlencode(local.aws_auth_users)
    } : {},
  )

  aws_auth_config_map = yamlencode({
    apiVersion = "v1"
    kind       = "ConfigMap"
    metadata = {
      name      = "aws-auth"
      namespace = "kube-system"
    }
    data = local.aws_auth_data
  })
}

output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_name
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "worker_security_group_id" {
  description = "Security group ids attached to the workers."
  value       = module.eks.node_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = yamlencode({
    apiVersion = "v1"
    kind       = "Config"
    clusters = [
      {
        name = module.eks.cluster_name
        cluster = {
          server                   = module.eks.cluster_endpoint
          "certificate-authority-data" = module.eks.cluster_certificate_authority_data
        }
      }
    ]
    contexts = [
      {
        name = module.eks.cluster_name
        context = {
          cluster = module.eks.cluster_name
          user    = module.eks.cluster_name
        }
      }
    ]
    "current-context" = module.eks.cluster_name
    preferences       = {}
    users = [
      {
        name = module.eks.cluster_name
        user = {
          exec = {
            apiVersion = "client.authentication.k8s.io/v1beta1"
            command    = "aws"
            args = [
              "eks",
              "get-token",
              "--cluster-name",
              module.eks.cluster_name,
              "--region",
              var.region,
            ]
          }
        }
      }
    ]
  })
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = local.aws_auth_config_map
}

output "worker_iam_role_arn" {
  description = "worker iam role arn"
  value       = local.worker_iam_role_arn
}

output "aws_eks_cluster_endpoint" {
  description = "Endpoint for EKS Cluster"
  value       = module.eks.cluster_endpoint
}

output "aws_eks_cluster_ca_certificate" {
  description = "CA Cert for Cluster authentication"
  value       = module.eks.cluster_certificate_authority_data
}

# output "aws_eks_cluster_token" {
#   description = "Token for Cluster authentication"
#   value       = data.aws_eks_cluster_auth.cluster.token
# }
